name: Deploy Documentation Website
on:
  push:
    branches:
      - main
jobs:
  run:
    name: Deploy GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install

      - name: Run Vuepress build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs

      - name: Purge TQ backend assets
        run: |
          curl -X GET "https://us-central1-twilioquest-prod.cloudfunctions.net/app/quest/api/v1/extension/purge/docs?auth=${{ secrets.EXTENSION_DOCS_DELETE_AUTH }}" -v
